services:
  - type: web
    name: btd-backend
    env: docker
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: DEV_MODE
        value: "false"
      - key: CORS_ALLOW_ORIGIN
        value: "https://YOUR-GITHUB-USERNAME.github.io"
